name: VPS
on:
  workflow_dispatch:

jobs:
  secure-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 ุณุงุนุงุช
    steps:
      - name: Start VPS (SSH + Ngrok)
        run: |
          echo "๐ข ุฅุนุฏุงุฏ VPS ููุฏ ุงูุชูููุฐ..."
          sudo apt update -y
          sudo apt install -y openssh-server curl unzip jq

          echo "๐ง ุชูุนูู SSH..."
          sudo systemctl enable ssh
          sudo systemctl start ssh
          echo "root:admin@123" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo service ssh restart
          echo "โ SSH ุฌุงูุฒ (user: root | pass: admin@123)"

          echo "๐ ุชุซุจูุช ngrok..."
          curl -sL https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip -o ngrok.zip
          unzip ngrok.zip
          sudo mv ngrok /usr/local/bin/ngrok

          # ๐ ุถุน ุชููู ngrok ุงูุฎุงุต ุจู ููุง
          NGROK_TOKEN="34EXIMZPmZ81T5fkUsj4Vqd6wdf_78WB47cQAGNXtchBbndEE"
          ngrok config add-authtoken $NGROK_TOKEN

          echo "๐ ุชุดุบูู ููู ngrok..."
          nohup ngrok tcp 22 --region eu > /dev/null 2>&1 &
          sleep 10

          echo "๐ต๏ธ ุงูุญุตูู ุนูู ุฑุงุจุท ุงูููู..."
          if ! curl -s http://127.0.0.1:4040/api/tunnels > /dev/null; then
            echo "โ ngrok ูู ูุจุฏุฃ ุจุนุฏุ ูุดู ุงูุงุชุตุงู ุจุงูู API."
            exit 1
          fi

          NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          if [ -z "$NGROK_URL" ] || [ "$NGROK_URL" = "null" ]; then
            echo "โ ูุดู ูู ุฌูุจ ุฑุงุจุท ngrok."
            exit 1
          fi

          echo "โ ngrok ูุนูู ุจูุฌุงุญ!"
          echo "------------------------------------"
          echo "๐ ูุนูููุงุช ุงูุงุชุตุงู:"
          echo "ssh root@${NGROK_URL#tcp://}"
          echo "๐ ูููุฉ ุงููุฑูุฑ: admin@123"
          echo "------------------------------------"

          echo "๐ ุฅุจูุงุก ุงูุณูุฑูุฑ ุดุบุงู..."
          while true; do
            echo "[$(date)] VPS running..."
            sleep 300
          done
